### ISSUE TITLE
cannot convert 'String' to 'const char*

### ISSUE THREAD

**Issue by RanMinecraft** [imrehorvath/BridgeHttpClient#2]
client.postAsync("https://httpbin.org/post", "{\"key\":\"value\"}");

Compilation error: cannot convert 'String' to 'const char*'

**Comment by imrehorvath** [comment]
Hello!
It looks like you try to use a `String` instead of the expected `const char*` in your code somewhere. You can either use `"my string"` directly, or `myString.c_str();` assuming myString is a `String`. Hint: if you submit a more detailed issue description, then a more specific reply can be given.

Please note that I've released a new version of this library, the 3.2.0, which adds support for `String` to the API.
